### ISSUE TITLE
Warning or Error?

### ISSUE THREAD

**Issue by un-fuf-a-doo** [offbeatbits/feed-notifier#27]
Hey I stumbled across your code and thought I would give it a try. I followed all of the steps in the Readme.md, but I am seeing the below output and despite not being a crash is not posting to my Mastodon application.

```
$ npm start --initialize

> feed-notifier@1.0.0 start
> node dist/index.js

(node:2191289) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at Function.get (/home/jpop/Projects/feed-notifier/dist/lib/cache.js:33:47)
    at getCachedArticle (/home/jpop/Projects/feed-notifier/dist/helpers/articles/getCachedArticle.js:9:35)
    at /home/jpop/Projects/feed-notifier/dist/commands/start.js:17:58
    at Generator.next (<anonymous>)
    at /home/jpop/Projects/feed-notifier/dist/commands/start.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/jpop/Projects/feed-notifier/dist/commands/start.js:4:12)
    at start (/home/jpop/Projects/feed-notifier/dist/commands/start.js:16:21)
(node:2191289) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2191289) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here is my .env file without actual credentials:

```
FN_FEED_URL='https://www.hackerone.com/blog.rss'
FN_CACHE_DIRECTORY='_cache'
FN_LOGGING_ENABLE='true'
FN_LOGGING_VERBOSE_ENABLE='true'
FN_TWITTER_ENABLE='false'
FN_TWITTER_USERNAME=''
FN_TWITTER_CLIENT_KEY=''
FN_TWITTER_CLIENT_SECRET=''
FN_TWITTER_CLIENT_ACCESS_TOKEN=''
FN_TWITTER_CLIENT_ACCESS_TOKEN_SECRET=''
FN_MASTODON_ENABLE='true'
FN_MASTODON_HOST='https://mstdn.hackdefendr.com'
FN_MASTODON_USERNAME='hackdefendr'
FN_MASTODON_CLIENT_KEY='xxxx'
FN_MASTODON_CLIENT_SECRET='xxxx'
FN_MASTODON_ACCESS_TOKEN='xxxx'
```

Am I missing something or making an error somewhere?

Regards,
Jeff

**Comment by lwojcik** [comment]
Hi Jeff! Thanks for letting me know. I'll see what's up and let you know.

**Comment by un-fuf-a-doo** [comment]
Awesome thanks for the response. Not sure if it helps, I tested this with NodeJS 12 on MacOS and Ubuntu.

**Comment by lwojcik** [comment]
Thanks for the details. I need a little more time to look at this. I'll report back by the end of next week.

**Comment by un-fuf-a-doo** [comment]
Awesome. There is no rush I'm just here to help test it out if I can.

**Comment by lwojcik** [comment]
Okay, I figured it out.

By default, the script assumes `NODE_ENV` to be equal to `development`. Otherwise it skips reading configuration details from `.env` file and tries to read them from the server environment variables. And if those are empty too, demons arise. :) 

For now, I made a quick and dirty fix for this issue in [opt_out_of_dotenv](https://github.com/offbeatbits/feed-notifier/tree/opt_out_of_dotenv) branch. Could you check if it fixes your problem?

**Comment by lwojcik** [comment]
Merged the fix. Let me know in case you have any other issues.

**Comment by un-fuf-a-doo** [comment]
Sorry for the delay in my reply. Work has me all over the place.  I will double check today to help prove the fix.

Thanks for doing this. I'm learning some JS and tools like these are how I do that.

Jeff

**Comment by lwojcik** [comment]
No worries, I'm always hpapy to help :)
